supply.feed-interval: 60000 # milliseconds

provider:
  name: xxx
  url: https://provider.code-challenge.funup.com/api/events
  timeout: 2000 #milliseconds

mongodb: 
  database.name: FunDataBase
  uri: ${MONGODB_URI}
  
server.port: 8080