services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: FunDataBase
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  fun-events-app:
    image: openjdk:20-jdk
    container_name: events-service
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      SPRING_PROFILES_ACTIVE: 'consumer'
    command: >
      bash -c "sleep 10 && java -jar /app/fun-events-start-app.jar"
    volumes:
      - ./fun-events-start-app.jar:/app/fun-events-start-app.jar
      
  xxx-provider:
    image: nginx:latest
    container_name: xxx-provider
    ports:
      - "80:80"
    volumes:
      - ./__files:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      
  fun-supply-app:
    image: openjdk:20-jdk
    container_name: supply-service
    depends_on:
      - mongo
      - xxx-provider
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      SPRING_PROFILES_ACTIVE: 'supply'
      PROVIDER_URL: 'http://xxx-provider/api/events'
    command: >
      bash -c "sleep 10 && java -jar /app/fun-events-start-supply.jar"
    volumes:
      - ./fun-events-start-supply.jar:/app/fun-events-start-supply.jar
      
