version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: FunDataBase
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  fever-events-app:
    image: openjdk:20-jdk
    container_name: events-service
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'  
    command: >
      bash -c "sleep 10 && java -jar /app/fever-events-start-app.jar"
    volumes:
      - ./fever-events-start-app.jar:/app/fever-events-start-app.jar
